// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbtOUfIA8WnfEYGrjMww3vwmh_hAPcvXw',
    appId: '1:1097492456079:web:becf35e60604efd8d186fa',
    messagingSenderId: '1097492456079',
    projectId: 'tutoria-v2',
    authDomain: 'tutoria-v2.firebaseapp.com',
    storageBucket: 'tutoria-v2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqP8wOYw16E0spoEwI5KKyjNvNNECcUrw',
    appId: '1:1097492456079:android:99bbdfa6380ba993d186fa',
    messagingSenderId: '1097492456079',
    projectId: 'tutoria-v2',
    storageBucket: 'tutoria-v2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBI8rp4Wui2pAlzsp8vel-HLx8Y7bWdkkM',
    appId: '1:1097492456079:ios:e3c6b993204143ddd186fa',
    messagingSenderId: '1097492456079',
    projectId: 'tutoria-v2',
    storageBucket: 'tutoria-v2.firebasestorage.app',
    iosBundleId: 'com.tutoria.tutoriaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBI8rp4Wui2pAlzsp8vel-HLx8Y7bWdkkM',
    appId: '1:1097492456079:ios:e3c6b993204143ddd186fa',
    messagingSenderId: '1097492456079',
    projectId: 'tutoria-v2',
    storageBucket: 'tutoria-v2.firebasestorage.app',
    iosBundleId: 'com.tutoria.tutoriaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBbtOUfIA8WnfEYGrjMww3vwmh_hAPcvXw',
    appId: '1:1097492456079:web:eb5bcdafe6841e7ed186fa',
    messagingSenderId: '1097492456079',
    projectId: 'tutoria-v2',
    authDomain: 'tutoria-v2.firebaseapp.com',
    storageBucket: 'tutoria-v2.firebasestorage.app',
  );
}
